USE [ehtplus]
GO

/****** Object:  Table [dbo].[TrendDevice]    Script Date: 3/1/2024 4:10:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TrendDevice](
	[TrendGroupGuid] [dbo].[GUID_IDENTIFIER] NOT NULL,
	[DeviceGuid] [dbo].[GUID_IDENTIFIER] NOT NULL,
 CONSTRAINT [PK_TRENDDEVICE] PRIMARY KEY CLUSTERED 
(
	[TrendGroupGuid] ASC,
	[DeviceGuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TrendDevice]  WITH CHECK ADD  CONSTRAINT [FK_TRENDDEV_RELATIONS_EHTDEVIC] FOREIGN KEY([DeviceGuid])
REFERENCES [dbo].[EHTDevice] ([DeviceGuid])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TrendDevice] CHECK CONSTRAINT [FK_TRENDDEV_RELATIONS_EHTDEVIC]
GO

ALTER TABLE [dbo].[TrendDevice]  WITH CHECK ADD  CONSTRAINT [FK_TRENDDEV_RELATIONS_EHTTREND] FOREIGN KEY([TrendGroupGuid])
REFERENCES [dbo].[EHTTrendGroup] ([TrendGroupGuid])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TrendDevice] CHECK CONSTRAINT [FK_TRENDDEV_RELATIONS_EHTTREND]
GO

