using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IC.RCS.RCSCore
{
    internal class Constants
    {

        public const string SQLTrendDataColumnTest =
            "ControlTemp float null, " +
            "ControlSetpoint float null, " +
             "HoursSinceReset int null, " +
             "HoursInUse int null, " +
             "ContactorCycleCount int null, " +
             "ControlTempMax float null, " +
             "ControlTempMin float null, " +
             "LocalTempSensorTempMax float null, " +
             "LocalTempSensorTempMin float null, " +
             "AverageAnalogsLastUpdate datetime null, " +
             "UnitMaintenanceLastUpdate datetime null, " +
             "SwitchMaintenanceLastUpdate datetime null, " +
             "MaxMinLastUpdate datetime null, " +
             "ControlTempFailed bit null, " +
             "CommPolls int null, " +
             "CommResponses int null, " +
             "CommRetries int null, " +
             "CommFailures int null, " +
             "LastParentReadTime datetime null, " +
             "LastSetpointUpdateTime datetime null, " +
             "LastUpdateTime datetime null, " +
             "ErrorStatus smallint null, " +
             "TS1Temp float null, " +
             "TS2Temp float null, " +
             "TS3Temp float null, " +
             "TS4Temp float null, " +
             "TempSource1Temp float null, " +
             "TempSource2Temp float null, " +
             "TempSource3Temp float null, " +
             "TempSource4Temp float null, " +
             "TempSource5Temp float null, " +
             "TempSource6Temp float null, " +
             "TempSource7Temp float null, " +
             "TempSource8Temp float null, " +
             "AmbientTemp float null, " +
             "LocalTempSensorTemp float null, " +
             "ControlOutputDutyCycle tinyint null, " +
             "PASCOnCount int null, " +
             "PASCOffCount int null, " +
             "PASCNextSwitchAction int null, " +
             "PASCOutputState int null, " +
             "TracingControlStatus smallint null, " +
             "EffectiveLineCurrent1 float null, " +
             "EffectiveLineCurrent2 float null, " +
             "EffectiveLineCurrent3 float null, " +
             "InstantanousGFI float null, " +
             "InstantLineCurrent1 float null, " +
             "InstantLineCurrent2 float null, " +
             "InstantLineCurrent3 float null, " +
             "Line2LineVoltage float null, " +
             "TracingResistance1 float null, " +
             "TracingResistance2 float null, " +
             "TracingResistance3 float null, " +
             "FixedFrequency int null, " +
             "PowerConsumption1 float null, " +
             "PowerConsumption2 float null, " +
             "PowerConsumption3 float null, " +
             "TotalPowerAllPhases float null, " +
             "LastOnLineCurrent1 float null, " +
             "LastOnLineCurrent2 float null, " +
             "LastOnLineCurrent3 float null, " +
             "LastOnEffectiveLineCurrent1 float null, " +
             "LastOnEffectiveLineCurrent2 float null, " +
             "LastOnEffectiveLineCurrent3 float null, " +
             "LastOnControlTemp float null, " +
             "LastOnGFI float null, " +
             "TotalPowerAllPhases_KWH int null, " +
             "PowerAccumulator1 int null, " +
             "PowerAccumulator2 int null, " +
             "PowerAccumulator3 int null, " +
             "PeakLineCurrent1 float null, " +
             "PeakLineCurrent2 float null, " +
             "PeakLineCurrent3 float null, " +
             "PeakGFCurrent float null, " +
             "HeaterTime int null, " +
             "RawDigitalInputLocRem bit null, " +
             "RawAlarmOutput bit null, " +
             "RawSSROutput bit null, " +
             "RawContactorOutput bit null, " +
             "LimiterTemperature float null, " +
            "BulkAlarm1 bigint null, " +
            "BulkAlarm2 bigint null"
            ;

        public const string SQLTrendDataColumns =
            "ControlTemp float null, " +
            "ControlSetpoint float null, " +
             "HoursSinceReset int null, " +
             "HoursInUse int null, " +
             "ContactorCycleCount int null, " +
             "ControlTempMax float null, " +
             "ControlTempMin float null, " +
             "LocalTempSensorTempMax float null, " +
             "LocalTempSensorTempMin float null, " +
             "AverageAnalogsLastUpdate datetime null, " +
             "UnitMaintenanceLastUpdate datetime null, " +
             "SwitchMaintenanceLastUpdate datetime null, " +
             "MaxMinLastUpdate datetime null, " +
             "ControlTempFailed bit null, " +
             "CommPolls int null, " +
             "CommResponses int null, " +
             "CommRetries int null, " +
             "CommFailures int null, " +
             "LastParentReadTime datetime null, " +
             "LastSetpointUpdateTime datetime null, " +
             "LastUpdateTime datetime null, " +
             "ErrorStatus smallint null, " +
             "TS1Temp float null, " +
             "TS2Temp float null, " +
             "TS3Temp float null, " +
             "TS4Temp float null, " +
             "TempSource1Temp float null, " +
             "TempSource2Temp float null, " +
             "TempSource3Temp float null, " +
             "TempSource4Temp float null, " +
             "TempSource5Temp float null, " +
             "TempSource6Temp float null, " +
             "TempSource7Temp float null, " +
             "TempSource8Temp float null, " +
             "AmbientTemp float null, " +
             "LocalTempSensorTemp float null, " +
             "ControlOutputDutyCycle tinyint null, " +
             "PASCOnCount int null, " +
             "PASCOffCount int null, " +
             "PASCNextSwitchAction int null, " +
             "PASCOutputState int null, " +
             "TracingControlStatus smallint null, " +
             "EffectiveLineCurrent1 float null, " +
             "EffectiveLineCurrent2 float null, " +
             "EffectiveLineCurrent3 float null, " +
             "InstantanousGFI float null, " +
             "InstantLineCurrent1 float null, " +
             "InstantLineCurrent2 float null, " +
             "InstantLineCurrent3 float null, " +
             "Line2LineVoltage float null, " +
             "TracingResistance1 float null, " +
             "TracingResistance2 float null, " +
             "TracingResistance3 float null, " +
             "FixedFrequency int null, " +
             "PowerConsumption1 float null, " +
             "PowerConsumption2 float null, " +
             "PowerConsumption3 float null, " +
             "TotalPowerAllPhases float null, " +
             "LastOnLineCurrent1 float null, " +
             "LastOnLineCurrent2 float null, " +
             "LastOnLineCurrent3 float null, " +
             "LastOnEffectiveLineCurrent1 float null, " +
             "LastOnEffectiveLineCurrent2 float null, " +
             "LastOnEffectiveLineCurrent3 float null, " +
             "LastOnControlTemp float null, " +
             "LastOnGFI float null, " +
             "TotalPowerAllPhases_KWH float null, " +
             "PowerAccumulator1 int null, " +
             "PowerAccumulator2 int null, " +
             "PowerAccumulator3 int null, " +
             "PeakLineCurrent1 float null, " +
             "PeakLineCurrent2 float null, " +
             "PeakLineCurrent3 float null, " +
             "PeakGFCurrent float null, " +
             "HeaterTime int null, " +
             "RawDigitalInputLocRem bit null, " +
             "RawAlarmOutput bit null, " +
             "RawSSROutput bit null, " +
             "RawContactorOutput bit null, " +
             "LimiterTemperature float null, " +
             "TS1TempMax float null, " +
             "TS1TempMin float null, " +
             "TS2TempMax float null, " +
             "TS2TempMin float null, " +
             "TS3TempMax float null, " +
             "TS3TempMin float null, " +
             "TS4TempMax float null, " +
             "TS4TempMin float null, " +
             "VoltageMax float null, " +
             "VoltageMin float null, " +
             "MaxCurrent float null, " +
             "MaxGroundFault float null, " +
             "LimiterTemperatureMax float null, " +
             "LimiterTemperatureMin float null, " +
            "RTD1Fail bit null, " +
            "RTD2Fail bit null, " +
            "RTD3Fail bit null, " +
            "RTD4Fail bit null, " +
            "RTD1Install bit null, " +
            "RTD2Install bit null, " +
            "RTD3Install bit null, " +
            "RTD4Install bit null, " +
            "PowerInputState bit null, " +
            "CBTripState bit null, " +
            "UserAlarmState bit null, " +
            "StatusLow int null, " +
            "StatusHigh int null, " +
            "LoopStatus3 int null, " +
            "LoopStatus4 int null, " +
            "LimiterNonLatching bit null, " +
            "LimiterTripped bit null, " +
            "BulkAlarm1 bigint null, " +
            "BulkAlarm2 bigint null";

    }
}
